strings = {
    'invalid_domain': ' is not a valid domain, please try again',
    'unresolved_domain_ip': ' is not available or cannot be reached right now, please check and try again later',
    'domain_required': 'Domain is required to scan',
    'auth': 'Authorization',
    'status_queued': 'queued',
    'status_running': 'running',
    'status_finished': 'finished',
    'domain-reputation': 'domain-reputation',
    'database_issue': 'Database connection issue',
    'key_value': 'value',
    'format_by_ip': 'format_by_ip',
    'key_ip': 'ip',
    'mongo_value': 'value',
    'input_force': 'force',
    'error': 'error',
    'message': 'message',
    'location': 'location',
}
